# Generated by Django 4.1.5 on 2023-02-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('parent_answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.answer')),
            ],
        ),
    ]
