# Generated by Django 4.1.5 on 2023-03-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
        ('answers', '0002_answer_author_answer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
