# Generated by Django 4.1.5 on 2023-02-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_supportresponse_parent_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportresponse',
            name='parent_response',
        ),
        migrations.AddField(
            model_name='supportresponse',
            name='support',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_responses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
