# Generated by Django 4.1.5 on 2023-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('FR', 'Frozen'), ('RE', 'Resolved')], default=('PE', 'Pending'), max_length=8),
        ),
    ]
